### ISSUE TITLE
Use Swagger Importer from AWS SDK

### ISSUE THREAD

**Issue by thoean** [Cimpress-MCP/LambdaWrap#6]
The AWS SDK / AWS Management Console / AWS CLI support importing swagger documentation. This got announced here: https://aws.amazon.com/about-aws/whats-new/2016/04/amazon-api-gateway-supports-swagger-definition-import/

LambdaWrap currently uses the aws-api-gateway-importer Java tool, which is an undesired dependency, especially since it needs to be custom built  due to a missing public binary. Just using the AWS SDK should be straight forward. The AWS Ruby SDK documentation for importing swagger files can be found at http://docs.aws.amazon.com/sdkforruby/api/Aws/APIGateway/Client.html#import_rest_api-instance_method.

**Comment by Shockolate** [comment]
As of writing, I am running into issues using the AWS CLI/SDK for importing an OpenAPI (swagger) Specification into API gateway. I get the vague error of  400: "Invalid Swagger 2.0 input." when using either the CLI or the webpage based importer. 
I have tried both .yaml and .json formats to no avail.
The aws-api-gateway-importer Java tool still works great with me API spec (with APIGateway extensions!).

These forum posts are tracking the issue:

- [Unusual Swagger validation in putRestApi/importRestApi](https://forums.aws.amazon.com/thread.jspa?messageID=714014&#714014)
Might not like $ref in responses...
- [No Recursive Definitions support](https://forums.aws.amazon.com/thread.jspa?messageID=714447)
- [Same error for CLI put-rest-api command](https://forums.aws.amazon.com/thread.jspa?messageID=714556)
- [No default response supported](https://forums.aws.amazon.com/thread.jspa?messageID=714239&#714239)

**Comment by amcp** [comment]
I am getting the same issues even when i feed in the petstore.json file.

**Comment by Shockolate** [comment]
Have they resolved the errors I outlined?

**Comment by thoean** [comment]
I don't know, therefore supporting both ways. For simple swagger files it works.

**Comment by ivictbor** [comment]
Hi possible issue in using single quotes or uncorrectly escaped characters. There are some difference in validating json by swagger web editor and aws more info https://maketips.net/tip/123/solve-invalid-swagger-20-input-when-import-swagger-to-aws-api-gateway
